Feature/add p number
itk-dev/naevnssekretariatet pull request #187
Opened 2022-03-28 11:30 UTC by jekuaitk

* Adds `pNumber` (P-nummer) to `Identification`
* Hides/shows `pNumber` form field based on `type` of `Identification`

2022-03-28 13:00 UTC, rimi-itk requested changes

2022-03-28 13:48 UTC, jekuaitk commented on assets/case/edit.js
> +  }
Good idea. Manually triggered `change`.

2022-03-28 16:06 UTC, rimi-itk requested changes

2022-03-28 16:06 UTC, rimi-itk commented on assets/case/edit.js
> +
You could also chain this when setting up the `click` handler, i.e.

```js
$(this)
  …
  .on('change', …)
  .trigger('change')
```

For consistency you should also to this in `new.js`.

2022-03-29 07:34 UTC, rimi-itk approved these changes

2022-03-29 07:35 UTC, merged