Feature/tvist1 437 hearing deadlines etc
itk-dev/naevnssekretariatet pull request #260
Opened 2022-08-18 09:31 UTC by jekuaitk

https://jira.itkdev.dk/browse/TVIST1-437

* Adds hearing response deadlines logic
*

2022-08-18 13:00 UTC, rimi-itk requested changes
Looks good. Some minor changes needed.

2022-08-18 13:39 UTC, jekuaitk commented on src/Entity/CaseEntity.php
> +    public function getHasReachedHearingResponseDeadline(): ?bool
Updated all boolean getters in 7326761d4ef857a3c6c7e7c40f79535e4cc31b5c.

2022-08-18 13:58 UTC, jekuaitk commented on src/Entity/CaseEntity.php
> +    public function getHasReachedHearingResponseDeadline(): ?bool
Woops, i was a little to quick here. This created a problem in our [logging](https://github.com/itk-dev/naevnssekretariatet/blob/feature/TVIST1-437-hearing-deadlines-etc/src/Logging/EntityListener/AbstractEntityListener.php#L134-L146).

2022-08-18 14:02 UTC, jekuaitk commented on src/Entity/CaseEntity.php
> +    public function getHasReachedHearingResponseDeadline(): ?bool
Reverted 7326761d4ef857a3c6c7e7c40f79535e4cc31b5c.

2022-08-19 07:12 UTC, rimi-itk approved these changes

2022-08-19 07:15 UTC, jekuaitk commented on src/EventSubscriber/PostPersist.php
> +class PostPersist implements EventSubscriberInterface
Renamed to `EntityPostPersistSubscriber` in 52570e2078cbb7a507edfc25b60a62f9fe0edf61.

2022-08-19 07:16 UTC, merged