Feature/tvist1 643 multiple complaint categories per case
itk-dev/naevnssekretariatet pull request #280
Opened 2022-11-02 08:30 UTC by jekuaitk

https://jira.itkdev.dk/browse/TVIST1-643

* Allows multiple complaint categories per case

2022-11-02 13:41 UTC, jekuaitk commented on fixtures/case_entity.yaml
> +    complaintCategories: ['@security-deposit-complaint-aarhus']
Added.

2022-11-02 13:41 UTC, jekuaitk commented on migrations/Version20221031135042.php
> +        // this down() migration is auto-generated, please modify it to your needs
Added.

2022-11-02 13:42 UTC, jekuaitk commented on src/Service/MailTemplate/ComplexMacroHelper.php
> +        $values['complaintCategories.name'] = new ComplexMacro(
Good idea. Updated.

2022-11-02 13:55 UTC, jekuaitk commented on src/Form/AgendaCaseItemNewType.php
> +                    }
Used `array_map` and `implode`.

2022-11-02 14:41 UTC, jekuaitk commented on src/Logging/EntityListener/AbstractEntityListener.php
> +            }
Updated.

2022-11-02 14:56 UTC, rimi-itk requested changes
One stylistic change needed. Consider using arrow functions.

2022-11-02 14:56 UTC, rimi-itk commented on src/Logging/EntityListener/AbstractEntityListener.php
> +            $complaintCategoryRemovals = array_map(static function (ComplaintCategory $complaintCategory) {
Umm, “arrow functions” …

2022-11-02 15:06 UTC, jekuaitk commented on migrations/Version20221031135042.php
> +        $this->addSql('UPDATE case_entity SET complaint_category_id = (SELECT complaint_category_id FROM case_entity_complaint_category WHERE case_entity_id = case_entity.id limit 1)');
Fixed.

2022-11-02 15:06 UTC, jekuaitk commented on src/Form/AgendaCaseItemNewType.php
> +                    $complaints = implode(', ', array_map(static function (ComplaintCategory $complaintCategory) {
Increased readability via arrow functions.

2022-11-02 15:06 UTC, jekuaitk commented on src/Logging/EntityListener/AbstractEntityListener.php
> +            $complaintCategoryRemovals = array_map(static function (ComplaintCategory $complaintCategory) {
Increased readability via arrow functions.

2022-11-03 08:46 UTC, rimi-itk approved these changes

2022-11-03 09:46 UTC, merged